<settings>

<repositories>
  <repository>
    <id>theconjars</id>
    <url>http://conjars.org/repo</url>
  </repository>
</repositories>

<mirrors>
  <mirror>
    <id>wenselconjars</id>
    <mirrorOf>theconjars</mirrorOf>
    <url>https://conjars.wensel.net/repo/</url>
  </mirror>
</mirrors>
</settings>