name: Compile Apache Ranger
on:
  push:
    branches:
      - 'main'

defaults:
  run:
    shell: 'bash -Eeuo pipefail -x {0}'

jobs:
  build:
    name: Build Apache Ranger
    runs-on: ubuntu-latest
    steps:
      - name: Download Apache Ranger
        id: download-ranger 
        run: |
          wget -nv "https://github.com/aligavahi/ranger/archive/refs/tags/ali_2.4.0.tar.gz" -O "apache-ranger.tar.gz"
          mkdir apache-ranger-2.4.0
          tar zxf apache-ranger.tar.gz -C apache-ranger-2.4.0
          cd apache-ranger-2.4.0
          java_version=$(cat pom.xml | grep -Eo "<java.version.required>.*</java.version.required>" | sed "s/<java.version.required>//g" | sed "s </java.version.required>  g")
          if [[ "$java_version" == "1.8" ]]; then
            java_version=8.0.345+1
          fi
          echo "::set-output name=java-version::$java_version"

      - name: Set up JDK ${{ steps.download-ranger.outputs.java-version }}
        uses: actions/setup-java@v3.9.0
        with:
          java-version: ${{ steps.download-ranger.outputs.java-version }}
          java-package: jdk
          architecture: x64
          distribution: temurin
          cache: 'maven'

      - name: Build Apache Ranger 2.4.0
        run: |
          cd apache-ranger-2.4.0        
          mvn clean compile package -DskipTests

      - name: Create release 2.4.0
        id: create-release
        uses: actions/create-release@v1.1.4
        env:
          ALI_TK: ${{ secrets.ALI_TK }}
        with:
          tag_name: 2.4.0
          release_name: Apache Ranger 2.4.0
          draft: false
          prerelease: false
        
      - name: Publish Apache Ranger 2.4.0
        run: |
          cd apache-ranger-2.4.0/target
          for asset in *.{tar.gz,jar}; do
            curl -H "Authorization: token ${{ secrets.ALI_TK }}" -H "Content-Type: $(file -b --mime-type $asset)" --data-binary @$asset "${{ steps.create-release.outputs.upload_url }}=$(basename $asset)"
          done

      - name: Checkout Apache Ranger compiled
        uses: actions/checkout@v3
        with:
          path: apache-ranger-compiled