name: Compile Apache Ranger
on:
  push:
    branches:
      - 'hive'

defaults:
  run:
    shell: 'bash -Eeuo pipefail -x {0}'

jobs:
  build:
    name: Build Apache Ranger
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 8.0.345+1
        uses: s4u/setup-maven-action@v1.7.0
        with:
          checkout-fetch-depth: 0
          java-version: 8.0.345+1
          java-distribution: temurin
          maven-version: 3.6.3

      - name: Create release 3.1.4
        id: create-release
        uses: actions/create-release@v1.1.4
        env:
          GITHUB_TOKEN: ${{ secrets.ALI_TK }}
        with:
          tag_name: 3.1.4
          release_name: custom Apache hive 3.1.4
          draft: false
          prerelease: false


      - name: build Apache Hive
        id: download-ranger 
        run: |
          wget -nv "https://github.com/aligavahi/hive/archive/refs/tags/release-3.1.4.tar.gz" -O "hive-3.1.4.tar.gz"
          tar zxf hive-3.1.4.tar.gz
          ls
          cd hive-release-3.1.4
          mvn clean compile package -DskipTests -Pdist --settings ../settings.yml
          ls
          cd packaging/target
          ls
          for asset in *.tar.gz; do
            curl -H "Authorization: token ${{ secrets.ALI_TK }}" -H "Content-Type: $(file -b --mime-type $asset)" --data-binary @$asset "${{ steps.create-release.outputs.upload_url }}=$(basename $asset)"
          done


      - name: Checkout Apache Hive compiled
        uses: actions/checkout@v3
        with:
          path: apache-ranger-compiled